export default {
  PLACE_RIVER: '강',
  PLACE_MOUTH: '강(하구)',
  PLACE_CLIFFTOP: '강(절벽위)',
  PLACE_POND: '연못',
  PLACE_OCEAN: '바다',
  PLACE_PIER: '바다(부둣가)',
  SIZE_NARROW: '길다',
  SIZE_XSMALL: '가장 작음',
  SIZE_SMALL: '작음',
  SIZE_MEDIUM: '보통',
  SIZE_LARGE: '큼',
  SIZE_XLARGE: '약간 큼',
  SIZE_XXLARGE: '가장 큼',
  HAS_FIN: '지느러미',
  HAS_SOUND: '울음소리',
  ALL_DAY: '하루종일 나타나요.',
};
